### ISSUE TITLE
autoSizeColumns = true does not work with newStreamingXlsx 

### ISSUE THREAD

**Issue by scottsteinbeck** [cfsimplicity/spreadsheet-cfml#253]
When setting autoSizeColumns with newStreamingXlsx, it exports fine but the column widths don't seem to scale correctly, they are all over the place.

Switching to newXlsx everything works as expected.

**Comment by scottsteinbeck** [comment]
I have a feeling this might be related to the asynchronous nature of the streaming xlsx, is there a way to know when the `addRows` is finished so I can manually call the `autoSizeColumn` on each of the columns?

**Comment by cfsimplicity** [comment]
Hi Scott. `addRows()` with `autoSizeColumns=true` should work fine on an SXSSF workbook and does for me.
```
xssfWorkbook = spreadsheet.newStreamingXlsx();
spreadsheet.addRows( workbook=xssfWorkbook, data=hugeQueryWithWideColumnData, autoSizeColumns=true );
spreadsheet.write( xssfWorkbook, filepath, true );
```
![autosize](https://user-images.githubusercontent.com/456718/126697803-79c5340d-b0a8-43e0-bef4-a53f5e7483bf.png)

Can you post some code that I can run to replicate what you're seeing?

**Comment by scottsteinbeck** [comment]
Here is a more complete understanding of what I'm experiencing with streamingXlsx.
I have a query and a separate header with header styles and header names.
My goal is to have the header row styled and to be included in the calculation for autoSizeWidth.

Upon some additional testing, it seems to be related to large sets of data

```
headerStyles =  {
  bold             : "true",
  alignment        : "center",
  verticalalignment: "center",
  fgColor          : "226,226,226",
  color            : "0,0,0",
  bottomBorder     : "MEDIUM",
  bottombordercolor: "0,0,0"
};
headerData = ['County','Old Ranch Name','Ranch','Field ID','Planted Acres','Total Acres','Commodity'];
spreadsheet.addRow ( workbook = workbook, data = headerData); 
spreadsheet.setRowHeight( workbook, 1, 23 );
spreadsheet.formatRow( workbook,headerStyles,1 );
data = [];
for(i=1;i<200;i++){
  data.push(['All','Cattle','Cattle Test','Test EastNorth','760','762.1','Cattle Pasture']);
  data.push(['All','Cattle','Cattle Pastures','Test EastSouth','594','609.2','Cattle Pastureasdfasd']);
  data.push(['All','Cattle','Cattle Test','Test Pasture','4586','4585.8','Cattle ']);
}
application.spreadsheet.addRows ( workbook = workbook, data = data, autoSizeColumns=true);
spreadsheet.download( workbook, "testautocolumns.xlsx");
```

**Comment by cfsimplicity** [comment]
Thanks for the code, Scott. This is what it produces:

![autosize1](https://user-images.githubusercontent.com/456718/135647309-68e12b49-80b3-4df0-9cc0-af30fb8b7c2a.png)

The data columns from row 2 onwards are auto sized to their values as expected, but the header row has not changed as it would do with a normal XLSX.

If I add `autoSizeColumns` to true when adding the header row...
```
spreadsheet.addRow ( workbook = workbook, data = headerData, autoSizeColumns=true ); 
```
...I get this:

![autosize2](https://user-images.githubusercontent.com/456718/135648167-4df0c3e4-bc83-45ad-8c9d-a96954e10945.png)

The first column is correctly auto sized to the header value, but columns B, E and F are not. So there is definitely a problem with `addRow()` +`autoSizeColumns` + streamingXlsx, which I'll need to look into. It would seem POI is doing something different with SXSSF.

Meantime, try using `addRows()` for the header, even though there's only one row. To do that just nest your header column array inside another array (since `addRows()` expects an array of arrays) and make sure you specify `autoSizeColumn`:
```
headerData = [ ['County','Old Ranch Name','Ranch','Field ID','Planted Acres','Total Acres','Commodity'] ];
spreadsheet.addRows( workbook = workbook, data = headerData, autoSizeColumns = true ); 
```
![autosize3](https://user-images.githubusercontent.com/456718/135649115-35ec5a95-c316-45e2-a122-1b19d0cf0e77.png)

**Comment by scottsteinbeck** [comment]
Thank you for the workaround, it worked great!
