### ISSUE TITLE
Date datatype converts date => datetime

### ISSUE THREAD

**Issue by scottsteinbeck** [cfsimplicity/spreadsheet-cfml#262]
Reproducible use case
```
  data = QueryNew( "Date", "VarChar", [ [  "2020-08-24" ] ] );
  datatypes = { date: [ "Date" ] };
  spreadsheet = New spreadsheet();
  workbook = spreadsheet.new();
  spreadsheet.addRows( workbook=workbook, data=data, datatypes=datatypes );
```

![Screen Shot 2021-10-01 at 12 46 08 AM](https://user-images.githubusercontent.com/5215594/135584216-6e9852eb-2238-4cca-8311-7f9573dccf51.png)

You can see that before it was a date with no time. after setting the datatype, the date now has a time of  7:00:00 AM

**Comment by cfsimplicity** [comment]
Hi Scott

Running your code I get different results. The value is showing as a date with no time in both Excel...

![20211001-excel](https://user-images.githubusercontent.com/456718/135630051-b1bd6e1b-cc13-4743-8678-1fe5aeb95bcf.png)
...and Libre Office

![20211001-libre](https://user-images.githubusercontent.com/456718/135630113-99dcfa25-eac0-44f0-8636-fce1b2e899cd.png)

Dates are actually stored as numbers in excel, whole ones for date only values, with fractions added for times.

To check what is actually being recorded in your workbook object, try adding the following code to your test case:
```
WriteDump( spreadsheet.getCellType( workbook, 1, 1 ) );
WriteDump( spreadsheet.getCellValue( workbook, 1, 1 ) );
spreadsheet.formatCell( workbook, { dataformat: "0.00000" }, 1, 1 );
WriteDump( spreadsheet.getCellValue( workbook, 1, 1 ) );
```
This is what I'm seeing, i.e. definitely a whole number, no time fractions:

![20211001-dump](https://user-images.githubusercontent.com/456718/135631811-0283cdb9-4183-44ae-9c34-5ced534f513c.png)

What do you get?

**Comment by scottsteinbeck** [comment]
I will say that i updated my timezone to reflect PST, I wonder if this is causing the issue. Though with a static date it shouldnt.
![Screen Shot 2021-10-01 at 9 54 57 AM](https://user-images.githubusercontent.com/5215594/135658697-6bf81fba-a047-4481-943d-412f18ea9835.png)

**Comment by scottsteinbeck** [comment]
Confirmed! Upon testing resetting the timezone inside lucee admin to the default (same as server), it has corrected the numeric value of the date
![image](https://user-images.githubusercontent.com/5215594/135659285-af0692dd-a1a8-4a58-8381-ce4807031516.png)

**Comment by scottsteinbeck** [comment]
I would assume this is a lucee issue and not a library issue correct?

**Comment by cfsimplicity** [comment]
I'm not sure it's necessarily either, although it's complicated and adding timezones into the mix makes it more so! I'm not an expert in this, but here's my current partial understanding.

The cell types the library lets you specify are `string`, `numeric`, `date`, `time`, `boolean` and `auto`. 

`date` and `time` both actually translate to a _datetime_ value, since that's all CF/POI/Excel understand.

The library will however try to identify "date only" and "time only" values and set the cell format to only display those portions of the datetime value in the cell. But the underlying datetime value is still stored in Excel as a number as explained above.

I don't fully understand the effect of changing the Lucee timezone, but I believe that POI/Excel uses the local machine timezone, so if there is a mismatch that will affect what POI stores.

Apparently POI does provide a way of specifying the timezone. I'll have a look at whether that could be a potential solution.

**Comment by cfsimplicity** [comment]
Forcing POI to match the Lucee timezone when setting date values does seem to fix the issue according to my tests. 

Please check with the latest develop branch, Scott, and if it's still not working for you just re-open the ticket.
